### ISSUE TITLE
[Error] Authors' page redirects to Maze 

### ISSUE THREAD

**Issue by LucianaMarques** [mlbench/mlbench-docs#7] opened 2019-03-04 20:02 UTC
The link to the authors' section is:

https://mlbench.readthedocs.io/en/latest/authors.html/

When trying to access the page via this hyperlink, it redirects to a 'Maze Found' page (basically it can't find it). But when accessing the section from the docs' main home, the display is just fine.

We need to find a way to fix it, since there is a link to it in the README.md files in the project's repositories.

**Comment by Panaetius** [comment] 2019-03-05 09:53
The issue is the extra `/` at the end.

The link is correct in the sidebar and main section at https://mlbench.readthedocs.io/en/latest/ 

I've fixed it in https://github.com/mlbench/mlbench-benchmarks/commit/ceca52a2a7bc4ebacd9aa8fa92ceb282566c1504 for `mlbench-benchmarks` Did you see the issue in any other repository?

**Comment by Panaetius** [comment] 2019-04-10 13:26
Closing since the original issue was fixed

**Closed** 2019-04-10 13:25 UTC
